name: Weekly GV SMS

on:
  workflow_dispatch:        # 支持手动触发
  schedule:
    - cron: '0 1 * * 1'     # 每周一 09:00 北京时间 = 01:00 UTC

jobs:
  send_sms_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Selenium
        run: pip install selenium

      - name: Setup Chromium
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser chromium-chromedriver

      - name: Run Selenium Script
        env:
          GV_EMAIL: ${{ secrets.GV_EMAIL }}
          GV_PASS: ${{ secrets.GV_PASS }}
        run: python send_weekly_sms.py
